#!/usr/bin/env bash
#-----------------------------------------------------------------------------------------------------------------
# Copyright (c) Zyrakq.
# Licensed under the MIT License or Apache License 2.0.
#-----------------------------------------------------------------------------------------------------------------
#
# Docs: https://github.com/zyrakq/arch-devcontainer-features/tree/master/src/pacman-mirror/README.md
# Maintainer: Zyrakq

set -e

# Read feature options
MODE="${MODE:-builtin}"
MIRRORLIST_URL="${MIRRORLISTURL:-}"
COUNTRY="${COUNTRY:-}"
PROTOCOL="${PROTOCOL:-https}"
MIRROR_COUNT="${MIRRORCOUNT:-10}"
UNCOMMENT_SERVERS="${UNCOMMENTSERVERS:-true}"

#-----------------------------------------------------------------------------------------------------------------
# Utility Functions
#-----------------------------------------------------------------------------------------------------------------

# Check if running as root
check_root() {
    if [ "$(id -u)" -ne 0 ]; then
        echo "ERROR: Script must be run as root" >&2
        exit 1
    fi
}

# Detect system type and architecture
detect_system() {
    ARCH=$(uname -m)
    
    # Detect OS from /etc/os-release
    if [ -f /etc/os-release ]; then
        . /etc/os-release
        if echo "$ID" | grep -qi "arch"; then
            if [ "$ARCH" = "x86_64" ]; then
                SYSTEM_TYPE="archlinux"
            elif [ "$ARCH" = "aarch64" ] || [ "$ARCH" = "armv7l" ]; then
                SYSTEM_TYPE="archlinuxarm"
            else
                echo "ERROR: Unsupported architecture: $ARCH" >&2
                exit 1
            fi
        else
            echo "ERROR: Not an Arch Linux based system" >&2
            exit 1
        fi
    else
        echo "ERROR: Cannot detect OS - /etc/os-release not found" >&2
        exit 1
    fi
    
    echo "Detected system: $SYSTEM_TYPE on $ARCH"
}

# Create backup of existing mirrorlist
create_backup() {
    if [ -f /etc/pacman.d/mirrorlist ]; then
        echo "Creating backup of existing mirrorlist..."
        cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.backup
        echo "Backup created at /etc/pacman.d/mirrorlist.backup"
    fi
}

# Download mirrorlist from URL
install_from_url() {
    local url="$1"
    echo "Downloading mirrorlist from: $url"
    
    if command -v curl &>/dev/null; then
        if ! curl -fsSL -o /etc/pacman.d/mirrorlist "$url"; then
            echo "ERROR: Failed to download mirrorlist from $url" >&2
            return 1
        fi
    elif command -v wget &>/dev/null; then
        if ! wget -q -O /etc/pacman.d/mirrorlist "$url"; then
            echo "ERROR: Failed to download mirrorlist from $url" >&2
            return 1
        fi
    else
        echo "ERROR: Neither curl nor wget available" >&2
        return 1
    fi
    
    # Uncomment servers if enabled
    if [ "$UNCOMMENT_SERVERS" = "true" ]; then
        echo "Uncommenting server lines..."
        sed -i 's/^#Server/Server/' /etc/pacman.d/mirrorlist
    fi
    
    echo "Mirrorlist downloaded successfully"
}

# Create builtin mirrorlist for x86_64 (Arch Linux)
create_builtin_x86_64() {
    cat > /etc/pacman.d/mirrorlist << 'EOF'
##
## Arch Linux repository mirrorlist
## Generated by pacman-mirror devcontainer feature
##

Server = https://at.arch.mirror.kescher.at/$repo/os/$arch
Server = https://mirror.theo546.fr/archlinux/$repo/os/$arch
Server = https://archlinux.thaller.ws/$repo/os/$arch
Server = https://mirror.moson.org/arch/$repo/os/$arch
Server = https://arch.phinau.de/$repo/os/$arch
Server = https://md.mirrors.hacktegic.com/archlinux/$repo/os/$arch
Server = https://london.mirror.pkgbuild.com/$repo/os/$arch
Server = https://mirrors.neusoft.edu.cn/archlinux/$repo/os/$arch
Server = https://mirror.ufscar.br/archlinux/$repo/os/$arch
Server = https://mirror.theash.xyz/arch/$repo/os/$arch
Server = https://america.mirror.pkgbuild.com/$repo/os/$arch
EOF
    echo "Builtin x86_64 mirrorlist created"
}

# Create builtin mirrorlist for ARM (Arch Linux ARM)
create_builtin_arm() {
    cat > /etc/pacman.d/mirrorlist << 'EOF'
##
## Arch Linux ARM repository mirrorlist
## Generated by pacman-mirror devcontainer feature
##

## GeoIP redirection (recommended)
Server = http://mirror.archlinuxarm.org/$arch/$repo

## Denmark
Server = http://dk.mirror.archlinuxarm.org/$arch/$repo

## Germany
Server = http://de3.mirror.archlinuxarm.org/$arch/$repo
Server = http://de.mirror.archlinuxarm.org/$arch/$repo
Server = http://de4.mirror.archlinuxarm.org/$arch/$repo
Server = http://eu.mirror.archlinuxarm.org/$arch/$repo

## Greece
Server = http://gr.mirror.archlinuxarm.org/$arch/$repo

## Hungary
Server = http://hu.mirror.archlinuxarm.org/$arch/$repo

## Taiwan
Server = http://tw2.mirror.archlinuxarm.org/$arch/$repo
Server = http://tw.mirror.archlinuxarm.org/$arch/$repo

## USA
Server = http://ca.us.mirror.archlinuxarm.org/$arch/$repo
Server = http://nj.us.mirror.archlinuxarm.org/$arch/$repo
Server = http://fl.us.mirror.archlinuxarm.org/$arch/$repo
EOF
    echo "Builtin ARM mirrorlist created"
}

# Create builtin mirrorlist based on system type
create_builtin_mirrorlist() {
    if [ "$SYSTEM_TYPE" = "archlinux" ]; then
        create_builtin_x86_64
    else
        create_builtin_arm
    fi
}

# Install using reflector mode
install_reflector_mode() {
    echo "Installing reflector mode..."
    
    # Step 1: Setup base mirrorlist first (required to install reflector)
    if [ -n "$MIRRORLIST_URL" ]; then
        echo "Setting up base mirrorlist from URL before installing reflector..."
        if ! install_from_url "$MIRRORLIST_URL"; then
            echo "Failed to download from URL, using builtin..."
            create_builtin_mirrorlist
        fi
    else
        echo "Setting up builtin mirrorlist before installing reflector..."
        create_builtin_mirrorlist
    fi
    
    # Step 2: Update package databases
    echo "Updating package databases..."
    pacman -Sy --noconfirm
    
    # Step 3: Install reflector
    echo "Installing reflector..."
    if ! pacman -S --noconfirm reflector; then
        echo "ERROR: Failed to install reflector" >&2
        return 1
    fi
    
    # Step 4: Build reflector command
    local reflector_cmd="reflector"
    
    # Add country filter
    if [ -n "$COUNTRY" ]; then
        IFS=',' read -ra country_array <<< "$COUNTRY"
        for country in "${country_array[@]}"; do
            reflector_cmd="$reflector_cmd --country $country"
        done
    fi
    
    # Add protocol filter
    if [ -n "$PROTOCOL" ]; then
        reflector_cmd="$reflector_cmd --protocol $PROTOCOL"
    fi
    
    # Add other options
    reflector_cmd="$reflector_cmd --latest $MIRROR_COUNT --sort rate"
    reflector_cmd="$reflector_cmd --save /etc/pacman.d/mirrorlist"
    
    # Step 5: Run reflector
    echo "Running reflector: $reflector_cmd"
    if ! eval "$reflector_cmd"; then
        echo "WARNING: reflector command failed, keeping current mirrorlist"
        return 1
    fi
    
    echo "Reflector mirrorlist generated successfully"
}

# Install using official archlinux.org API mode
install_official_mode() {
    echo "Installing official mirrorlist mode..."
    
    # Official mode only supported for x86_64 Arch Linux
    if [ "$SYSTEM_TYPE" = "archlinuxarm" ]; then
        echo "WARNING: Official mode not supported for ARM, falling back to builtin"
        create_builtin_mirrorlist
        return
    fi
    
    echo "Downloading mirrorlist from archlinux.org..."
    
    # Build API URL with filters
    local api_url="https://archlinux.org/mirrorlist/?use_mirror_status=on"
    
    # Add country parameters
    if [ -n "$COUNTRY" ]; then
        IFS=',' read -ra country_array <<< "$COUNTRY"
        for country in "${country_array[@]}"; do
            api_url="${api_url}&country=${country}"
        done
    fi
    
    # Add protocol parameter
    [ -n "$PROTOCOL" ] && api_url="${api_url}&protocol=$PROTOCOL"
    
    echo "API URL: $api_url"
    
    # Download mirrorlist
    if command -v curl &>/dev/null; then
        if [ "$UNCOMMENT_SERVERS" = "true" ]; then
            # Download and uncomment server lines
            if ! curl -fsSL "$api_url" | sed 's/^#Server/Server/' > /etc/pacman.d/mirrorlist; then
                echo "ERROR: Failed to download official mirrorlist" >&2
                return 1
            fi
        else
            # Download as-is
            if ! curl -fsSL "$api_url" > /etc/pacman.d/mirrorlist; then
                echo "ERROR: Failed to download official mirrorlist" >&2
                return 1
            fi
        fi
    elif command -v wget &>/dev/null; then
        if [ "$UNCOMMENT_SERVERS" = "true" ]; then
            # Download and uncomment server lines
            if ! wget -q -O- "$api_url" | sed 's/^#Server/Server/' > /etc/pacman.d/mirrorlist; then
                echo "ERROR: Failed to download official mirrorlist" >&2
                return 1
            fi
        else
            # Download as-is
            if ! wget -q -O- "$api_url" > /etc/pacman.d/mirrorlist; then
                echo "ERROR: Failed to download official mirrorlist" >&2
                return 1
            fi
        fi
    else
        echo "ERROR: Neither curl nor wget available" >&2
        return 1
    fi
    
    echo "Official mirrorlist downloaded and configured"
}

#-----------------------------------------------------------------------------------------------------------------
# Main Execution
#-----------------------------------------------------------------------------------------------------------------

echo "Starting pacman-mirror feature installation..."

# Run prerequisite checks
check_root
detect_system
create_backup

# Install mirrorlist based on mode
case "$MODE" in
    builtin)
        echo "Mode: builtin - using embedded mirrorlist"
        create_builtin_mirrorlist
        ;;
    url)
        echo "Mode: url - downloading from custom URL"
        if [ -z "$MIRRORLIST_URL" ]; then
            echo "ERROR: mirrorlistUrl is required when mode=url" >&2
            exit 1
        fi
        install_from_url "$MIRRORLIST_URL"
        ;;
    reflector)
        echo "Mode: reflector - using reflector for auto-selection"
        install_reflector_mode
        ;;
    official)
        echo "Mode: official - using archlinux.org API"
        install_official_mode
        ;;
    *)
        echo "ERROR: Invalid mode: $MODE" >&2
        echo "Valid modes: builtin, url, reflector, official" >&2
        exit 1
        ;;
esac

# Final sync of package databases
echo "Synchronizing package databases..."
pacman -Sy

echo "Pacman mirrorlist configuration completed successfully!"
